name: Maven CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build project with Maven
      run: mvn -B package --file pom.xml

    - name: Upload JAR as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: "HolographicDisplays Jar"
        path: plugin/target/holographicdisplays-*.jar
        if-no-files-found: error